name: Use Append Wow Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - "test.py"
  repository_dispatch:
    types:
      - shared-workflow-updated
  

jobs:
  append-wow:
    uses: sonicavionics/shared-workflows/.github/workflows/actiontest.yml@main
