jobs:
  export-kicad-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Pull KiCad Docker image
      - name: Pull KiCad Docker image
        run: |
          echo "Pulling KiCad Docker image..."
          docker pull kicad/kicad:8.0

      # Run KiCad Docker container to export files
      - name: Export schematic, PCB, and 3D model
        run: |
          echo "Exporting schematic, PCB, and 3D model..."
          docker run --rm -v "${{ github.workspace }}:/workspace" kicad/kicad:8.0 bash -c "
            cd /workspace

            # Export schematic
            mkdir -p images
            kicad-cli sch export svg -o 'images/sch.svg' kicad/*.kicad_sch

            # Export PCB
            kicad-cli pcb export svg -o 'images/pcb.svg' --page-size-mode 2 --exclude-drawing-sheet --layers 'F.Cu,F.SilkS,F.Mask' kicad/*.kicad_pcb

            # Export 3D model
            kicad-cli pcb export step --output 'images/board.step' kicad/*.kicad_pcb
            cd ..
          "

      # Notify the user about completion
      - name: Notify completion
        run: echo "Schematic, PCB, and 3D model exported successfully into the 'images' directory."
