# .github/workflows/use-export-kicad.yml
name: Call Test Reusable Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.kicad_sch'
      - '**/*.kicad_pcb'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  call-test2:
    uses: sonicavionics/shared-workflows/.github/workflows/test.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

