# .github/workflows/use-export-kicad.yml
name: test
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.kicad_sch'
      - '**/*.kicad_pcb'
jobs:
  call-workflow:
    uses: sonicavionics/shared-workflows/.github/workflows/test.yml@main
