name: test2

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      
      - name: Create GitHub App token
        id: create_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.MY_APP_ID }}
          private_key: ${{ secrets.MY_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.MY_APP_INSTALLATION_ID }}

      - name: Configure Git
        run: |
          git config user.name "Your GitHub App"
          git config user.email "123456+YourApp[bot]@users.noreply.github.com"

      - name: Commit changes using the App token
        run: |
          git add images/*
          git commit -m "Auto-export from GitHub App" || echo "No changes to commit."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ steps.create_app_token.outputs.token }}

